import { ackInjector } from "./ackInjector";
import * as ackObject from "./object";
import { jError } from "./error";
export declare function throwBy(ob: any, msg: any): void;
export declare function logArrayTo(array: any, logTo: any): void;
export declare function logError(err: any, msg: any, logTo: any): void;
export declare function injector($scope: any): ackInjector;
export declare function promise(var0?: any, var1?: any, var2?: any, var3?: any): any;
export declare function PromiseFunction(resolver: any): any;
export declare const ackAppends: {
    modules: ackInjector;
    object: typeof ackObject;
    throwBy: typeof throwBy;
    logArrayTo: typeof logArrayTo;
    logError: typeof logError;
    injector: typeof injector;
    promise: typeof promise;
    Promise: typeof PromiseFunction;
};
export declare class ackExpose {
    $var: any;
    constructor($var: any);
    ackit(name: any): any;
    static ackit(name: any): any;
    ackGet(name: any): any;
    throwBy: typeof throwBy;
    logArrayTo: typeof logArrayTo;
    logError: typeof logError;
    injector: typeof injector;
    promise: typeof promise;
    Promise: typeof PromiseFunction;
    error(v: any): jError;
    number(v: any): any;
    string(v: any): any;
    binary(v: any): any;
    base64(v: any): any;
    method(v: any): any;
    array(v: any): any;
    queryObject(v: any): any;
    week(v: any): any;
    month(v: any): any;
    year(v: any): any;
    date(v: any): any;
    time(v: any): any;
    function(): any;
    getSimpleClone(): {};
    get(name: any, def?: any): any;
    byName(name: any): ackExpose;
    throw(msg: any, logTo: any): this;
    stringify(spacing: any): string;
    dump(spacing: any): string;
    getBit(): 0 | 1;
    nullsToEmptyString(): this;
    getBoolean(): Number | Boolean;
    isBooleanLike(): boolean;
}
export declare function ack($var: any): ackExpose;
export declare namespace ack {
    var error: (v: any) => jError;
}
